### ISSUE TITLE
Support ingressClassName setting

### ISSUE THREAD

**Issue by zengzhengrong** [apache/pulsar-helm-chart#333]
### 
annotations is not recommended
```
  ingress:
    enabled: false
    annotations: 
       annotations.kubernetes.io/ingress.class: "nginx"
    tls:
      enabled: false

      ## Optional. Leave it blank if your Ingress Controller can provide a default certificate.
      secretName: ""

    hostname: ""
    path: "/"
```

Use ```ingressClassName```

```
  ingress:
    enabled: false
    ingressClassName: "nginx"
```
