### ISSUE TITLE
 I set kop-related parameters in broker-configmap.yaml and failed to take effect

### ISSUE THREAD

**Issue by tianshimoyi** [apache/pulsar-helm-chart#340]
**Describe the bug**
 I set kop-related parameters in broker-configmap.yaml and failed to take effect.
version: pulsar-helm-char:4.9.4

Broker settings
```yaml
# Broker settings
  clusterName: {{ template "pulsar.cluster.name" . }}
  exposeTopicLevelMetricsInPrometheus: "true"
  numHttpServerThreads: "8"
  zooKeeperSessionTimeoutMillis: "30000"
  statusFilePath: "{{ template "pulsar.home" . }}/status"
  brokerDeleteInactivePartitionedTopicMetadataEnabled: "false"
  brokerDeleteInactiveTopicsEnabled: "false"
  allowAutoTopicCreation: "false"
  allowAutoSubscriptionCreation: "false"
  managedLedgerDefaultEnsembleSize: "3"
  managedLedgerDefaultWriteQuorum: "2"
  managedLedgerDefaultAckQuorum: "2"
  messagingProtocols: kafka
  saslAllowedMechanisms: PLAIN
  protocolHandlerDirectory: "./protocols"
  allowAutoTopicCreationType: "partitioned"
  kafkaListeners: PLAINTEXT://127.0.0.1:9092
  kafkaAdvertisedListeners: PLAINTEXT://127.0.0.1:9092
  brokerEntryMetadataInterceptors: org.apache.pulsar.common.intercept.A
```

Result:
<img width="792" alt="截屏2022-12-02 下午5 23 37" src="https://user-images.githubusercontent.com/68532999/205259949-23dddc82-14b4-4a2e-a2d0-9fb35f48de73.png">
