### ISSUE TITLE
k8s flux install 3.0.0 error

### ISSUE THREAD

**Issue by MABIY** [apache/pulsar-helm-chart#345]
**Describe the bug**
k8s use flux install helm 3.0.0 error.
k8s version: v1.24.6
**To Reproduce**
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pulsar
spec:
  interval: 168h
  url: https://pulsar.apache.org/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pulsar
spec:
  chart:
    spec:
      chart: pulsar
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pulsar
      version: 3.0.0
      interval: 168h
  interval: 10m
  values:
    initialize: true
    kube-prometheus-stack:
      enabled: false
      prometheusOperator:
        enabled: false
      grafana:
        enabled: false
      alertmanager:
        enabled: false
      prometheus:
        enabled: false
```

**Expected behavior**
install success

**helm controler info**
```shell
{"level":"error","ts":"2022-12-22T03:37:05.293Z","msg":"Reconciler error","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"pulsar","namespace":"iccip-dev"},"namespace":"iccip-dev","name":"pulsar","reconcileID":"7964bf69-04ce-44f6-86d5-9cee119560ec","error":"Helm install failed: unable to build kubernetes objects from release manifest: [resource mapping not found for name: \"pulsar-recovery\" namespace: \"\" from \"\": no matches for kind \"PodMonitor\" in version \"monitoring.coreos.com/v1\"\nensure CRDs are installed first, resource mapping not found for name: \"pulsar-bookie\" namespace: \"\" from \"\": no matches for kind \"PodMonitor\" in version \"monitoring.coreos.com/v1\"\nensure CRDs are installed first, resource mapping not found for name: \"pulsar-broker\" namespace: \"\" from \"\": no matches for kind \"PodMonitor\" in version \"monitoring.coreos.com/v1\"\nensure CRDs are installed first, resource mapping not found for name: \"pulsar-proxy\" namespace: \"\" from \"\": no matches for kind \"PodMonitor\" in version \"monitoring.coreos.com/v1\"\nensure CRDs are installed first, resource mapping not found for name: \"pulsar-zookeeper\" namespace: \"\" from \"\": no matches for kind \"PodMonitor\" in version \"monitoring.coreos.com/v1\"\nensure CRDs are installed first]"}

```

**Comment by mouchar** [comment]
If you disabled kube-prometheus-stack and you don't have another prometheus stack installed, you probably miss the PodMonitor CRDs. If you don't need to monitor your pulsar deployment, you may disable installing PodMonitor resources by setting:

```yaml
zookeeper:
  podMonitor:
    enabled: false
broker:
  podMonitor:
    enabled: false
bookkeeper:
  podMonitor:
    enabled: false
broker:
  podMonitor:
    enabled: false
proxy:
  podMonitor:
    enabled: false
```

**Comment by MABIY** [comment]
@mouchar thanks you.
l'm disabled all podMonitor like below ,install success.
```yaml
    proxy:
      podMonitor:
        enabled: false
    broker:
      podMonitor:
        enabled: false
    zookeeper:
      podMonitor:
        enabled: false
    autorecovery:
      podMonitor:
        enabled: false
    bookkeeper:
      podMonitor:
        enabled: false

```
