### ISSUE TITLE
[bookie] InvalidCookieException on fresh install of Pulsar chart v3.0.0

### ISSUE THREAD

**Issue by MisterTimn** [apache/pulsar-helm-chart#347]
**Describe the bug**
When initializing a new Pulsar cluster on k8s v1.22.17 the bookkeepers crashloop with `InvalidCookieException`.

```
pulsar-bookie 2023-02-09T12:41:47,136+0000 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server pulsar-bookie org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: instanceId 70fa10af-86ef-4ced-b307-75f998c2ab8d is not matching with 2024bf46-92f4-4
```

It's as if something has gone wrong with the initializing processes, wrong IDs that are stored in Zookeeper?

I have retried and made sure to delete previous PVCs and secrets between installs, to no avail.

**To Reproduce**

Our values file:
```yaml
affinity:
  anti_affinity: true
  type: preferredDuringSchedulingIgnoredDuringExecution
auth:
  authentication:
    enabled: false
bookkeeper:
  replicaCount: 3
  resources:
    requests:
      cpu: 0.2
      memory: 1Gi
  volumes:
    journal:
      local_storage: false
      name: journal
      size: 10Gi
      storageClassName: idlab-ssd
    ledgers:
      local_storage: false
      name: ledgers
      size: 100Gi
      storageClassName: idlab-ssd
    persistence: true
broker:
  replicaCount: 3
  resources:
    requests:
      cpu: 0.2
      memory: 1Gi
components:
  autorecovery: true
  bookkeeper: true
  broker: true
  functions: false
  proxy: false
  pulsar_manager: false
  toolset: true
  zookeeper: true
initialize: true
kube-prometheus-stack:
  enabled: false
namespace: v3-pulsar
namespaceCreate: false
tls:
  enabled: false
toolset:
  useProxy: false
volumes:
  local_storage: false
  persistence: true
zookeeper:
  replicaCount: 3
  resources:
    requests:
      cpu: 0.1
      memory: 256Mi
  volumes:
    data:
      local_storage: false
      name: data
      size: 20Gi
      storageClassName: idlab-ssd
    persistence: true
```

1. Create v1.22.x cluster
2. `helm install pulsar apache/pulsar -f values.yaml`
3. Check status of bookies

**Expected behavior**
Bookies come up and are initiated with a correct instance ID.

**Desktop (please complete the following information):**
 - k8s: v1.22.17
 - helm: v3.11.1

**Additional context**
I know we are deploying on a no longer supported version of Kubernetes, but this is to test an upgrade path for a "neglected" cluster in dire need of seemless upgrading.
