### ISSUE TITLE
spec.values.rbac.limit_to_namespace=true  not fix  'ClusterRole exists and cannot be imported into the current release'

### ISSUE THREAD

**Issue by MABIY** [apache/pulsar-helm-chart#352]
**Describe the bug**
spec.values.rbac.limit_to_namespace=true not fix  'ClusterRole exists and cannot be imported into the current release.'

**To Reproduce**
1. create new namepspace 
2.  flux add in different namespace 
   ```yaml
  apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: HelmRepository
  metadata:
    name: pulsar
  spec:
    interval: 168h
    url: https://pulsar.apache.org/charts
  ---
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: pulsar
  spec:
    chart:
      spec:
        chart: pulsar
        reconcileStrategy: ChartVersion
        sourceRef:
          kind: HelmRepository
          name: pulsar
        version: 3.0.0
        interval: 168h
    interval: 10m
    values:
      kube-prometheus-stack:
        enabled: false
        prometheusOperator:
          enabled: false
        grafana:
          enabled: false
        alertmanager:
          enabled: false
        prometheus:
          enabled: false
      initialize: true
      rbac:
        enabled: true
        limit_to_namespace: true
      proxy:
        podMonitor:
          enabled: false
        replicaCount: 1
        service:
          type: ClusterIP
      broker:
        podMonitor:
          enabled: false
        replicaCount: 1
        probe:
          readiness:
            initialDelaySeconds: 60
        resources:
          requests:
            memory: 4Gi
            cpu: 1
      zookeeper:
        podMonitor:
          enabled: false
        replicaCount: 1
        volumes:
          data:
            size: 20Gi
      autorecovery:
        podMonitor:
          enabled: false
      bookkeeper:
        podMonitor:
          enabled: false
        volumes:
          journal:
            size: 20Gi
        replicaCount: 1
        resources:
          requests:
            memory: 4Gi
            cpu: 0.5
   ```

**Expected behavior**
install pulsar helm chart  successed.

**Additional context**
k8s : v1.25.6
flux version 0.40.2
pulsar helm version 3.0.0

error log:
```log
Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "pulsar-functions-worker" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "iccip-staging": current value is "iccip-dev" Last Helm logs: CRD prometheusrules.monitoring.coreos.com is already present. Skipping. creating 1 resource(s) CRD servicemonitors.monitoring.coreos.com is already present. Skipping. creating 1 resource(s) CRD thanosrulers.monitoring.coreos.com is already present. Skipping.
```
