### ISSUE TITLE
Pulsar Broker JVM Arguments are Ignored

### ISSUE THREAD

**Issue by tsteinholz** [apache/pulsar-helm-chart#389]
**Describe the bug**

Increasing pods requests / limits and even manually specifying the JVM memoryOptions has no affect on the pod JVM allocation.

**To Reproduce**

Attempt to configure Pulsar broker JVM configurations with just broker requests

```
  broker:
    resources:
      requests:
        memory: "8Gi"
        cpu: "0.2"
      limits: {}
        # memory: "2Gi"
        # cpu: "0.8"
```
Or try to manually specify the JVM size
```
      jvm:
      # Pulsar Operator will automatically generate the JVM memory options based on the Pod memory size. You can override this by entering a new value. (False or misleading statement)
        memoryOptions:
          - >
            -Xms2g
            -Xmx2g
            -XX:MaxDirectMemorySize=4g 
```

**Expected behavior**

The pods should be allocated with requested JVM memory options that are specified in the release
```
      jvm:
        memoryOptions:
        - "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g \n"
```

Actual Behavior:
```
PULSAR_MEM : -Xms153m -Xmx153m -XX:MaxDirectMemorySize=307m
```

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tsteinholz** [comment]
Using the `@deprecated` config map field in the values.yaml also fails

```
    broker:
      configData:
        PULSAR_MEM: >
          -Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g
```
https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/values.yaml#L758C14-L758C14
