### ISSUE TITLE
Bug in podAntiAffinity labels

### ISSUE THREAD

**Issue by mkozioro** [apache/pulsar-helm-chart#39]
**Describe the bug**
I've noticed, that multiple zookeeper pods started on same kubernetes node. It looks like issue with labels and podAntiAffinity settings.
Example using zookeeper

koziorow@pl1lxl-108450:~/projects/LNS-DevEnv/repo/batch-service-infra/terraform-apache-pulsar$ kubectl describe pod pulsar-zookeeper-0 
Name:         pulsar-zookeeper-0
Namespace:    default
Priority:     0
Node:         aks-default-12797261-vmss000001/10.240.0.115
Start Time:   Mon, 13 Jul 2020 12:22:02 +0200
Labels:       **app=pulsar**
              cluster=pulsar
              component=zookeeper
              controller-revision-hash=pulsar-zookeeper-7d87bf67f9
              release=pulsar
              statefulset.kubernetes.io/pod-name=pulsar-zookeeper-0

In chart:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                **- "{{ template "pulsar.name" . }}-{{ .Values.zookeeper.component }}"**
              - key: "release"
                operator: In
                values:
                - {{ .Release.Name }}
              - key: "component"
                operator: In
                values:
                - {{ .Values.zookeeper.component }}
            topologyKey: "kubernetes.io/hostname"

**Expected behavior**
Zookeeper pods should start on different nodes. Problem exists also in other components. 
BTW. Maybe it would be useful to use recommended helm labels? https://helm.sh/docs/chart_best_practices/labels/
Also I'm not sure, but there could be also copy-paste issue in https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/autorecovery-statefulset.yaml with:
```
              - key: "component"
                operator: In
                values:
                - {{ .Values.bookkeeper.component }}
```

**Comment by sijie** [comment]
@mkozioro Thank you for reporting this issue. Are you interested in contributing a bug fix?

**Comment by mkozioro** [comment]
Sure, I can prepare PR.

**Comment by rvashishth** [comment]
I was about to create an issue for standard helm lable and annotations. These will be important to migrate this chart from helm 2 to helm 3. 

We should also upgrade the chart api to version 3.

**Comment by sijie** [comment]
@rvashishth sounds like a good idea. +1

**Comment by mkozioro** [comment]
Hi @rvashishth 

I suppose you have better knowledge about migrating to new helm 3 than me. I know only about changed labels. Maybe you would like to migrate this chart and with labels, fix podAntiAffinity?

**Comment by rvashishth** [comment]
Sure. I can take this.

**Comment by rvashishth** [comment]
@mkozioro I tried the anti-affinity on AKS, but I can see pods are scheduled on different AKS nodes as expected. I have tested with 3 node-pool, 3 zookeeper pods.

**Comment by mkozioro** [comment]
@rvashishth Could you try with 3 node pool and 5 zookeepers? If affinity works OK, 2 new nodes should be always created. When I was testing couple days ago, I've got 2 zookeepers running on same node.

**Comment by rvashishth** [comment]
@mkozioro which cloud are you using, I could see the behavior as you mentioned on Azure AKS.

**Comment by mkozioro** [comment]
Hi @rvashishth 
I'm also using AKS. 1.16.x and 1.17.x.

**Comment by rvashishth** [comment]
@mkozioro if you have a fix handly, please feel free to contribute.

**Comment by toneill818** [comment]
@rvashishth The bug is in the labelSelector for podAntiAffinity. 
```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
        matchExpressions:
          - key: "app"
            operator: In
            values:
              - "{{ template "pulsar.name" . }}-{{ .Values.zookeeper.component }}" # This is where the issue is, it will never match
```
The app is set to pulsar.name-component. So it looks for app: pulsar-zookeeper, but the template for the labels sets the app to pulsar.name. Removing the "-component" should fix this. I can open a PR with this fix if you would like. Also with this change you will need to have as many nodes as the highest replicas for any of the stateful sets. Should we set the affinity to `preferredDuringSchedulingIgnoredDuringExecution`?
