### ISSUE TITLE
Pulsar broker fails to start: Required clusterName is null

### ISSUE THREAD

**Issue by bowen-facere** [apache/pulsar-helm-chart#396]
**Describe the bug**
When the broker container starts up it throws the exception 
```
2023-10-06T06:53:09,037Z [jdk.internal.loader.ClassLoaders$AppClassLoader@5bc2b487] error Uncaught exception in thread main: Required clusterName is null
java.lang.IllegalArgumentException: Required clusterName is null
	at org.apache.pulsar.common.configuration.PulsarConfigurationLoader.isComplete(PulsarConfigurationLoader.java:153)
	at org.apache.pulsar.PulsarBrokerStarter.loadConfig(PulsarBrokerStarter.java:73)
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.<init>(PulsarBrokerStarter.java:169)
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:333)
```

**To Reproduce**
1. Using this `values.yaml`
```
clusterName: pulsar-test
components:
  zookeeper: true
  bookkeeper: true
  broker: true
  autorecovery: false
  functions: false
  proxy: false
  toolset: false
  pulsar_manager: false
images:
  zookeeper:
    repository: apachepulsar/pulsar-all
    tag: 3.1.0
    pullPolicy: IfNotPresent
  bookie:
    repository: apachepulsar/pulsar-all
    tag: 3.1.0
    pullPolicy: IfNotPresent
  broker:
    repository: apachepulsar/pulsar-all
    tag: 3.1.0
    pullPolicy: IfNotPresent
volumes:
  persistence: true
  data:
    name: data
    size: 5Gi
    local_storage: true
bookkeeper:
  component: bookie
  replicaCount: 1
broker:
  component: broker
  replicaCount: 1
  ports:
    pulsar: 6650
zookeeper:
  component: zookeeper
  replicaCount: 1
ports:
  client: 2181
kube-prometheus-stack:
  enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  alertmanager:
    enabled: false
 ```
2. Run `helm install pulsar-test apache/pulsar -f values.yaml`
3. Run `kubectl get pods` and observe that broker container is the the `CrashLoopBackOff` status

**Expected behavior**
The broker container starts up without errors.

**Screenshots**
Container is in CrashLoopBackOff
<img width="607" alt="image" src="https://github.com/apache/pulsar-helm-chart/assets/137258060/3009cf98-e97d-4307-a107-7e6161dc428f">
The log inside the container:
<img width="1099" alt="image" src="https://github.com/apache/pulsar-helm-chart/assets/137258060/092bdf92-34c5-48f0-be29-cb83169c5e6b">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - K3s verison: v1.27.5+k3s1
