### ISSUE TITLE
Pulsar Manager v0.4.0 in kubernetes still can not persist any data

### ISSUE THREAD

**Issue by wuyudian1** [apache/pulsar-helm-chart#470]
**Describe the bug**
I upgraded our Pulsar to Chart v3.3.0, and the custom values for Pulsar Manager are as follows:
```yml
pulsar_manager:
  nodeSelector:
    pulsar: "true"
  service:
    type: ClusterIP
  volumes:
    data:
      storageClassName: ebs-gp3
      local_storage: false
      size: 1Gi
```
After creating an environment and some tenants in the web console, I restarted the Pulsar Manager pod to verify whether the data would be persisted. The result was that no data was persisted. I had to recreate the admin user and environment via the REST API.

In the Pulsar Manager POD, the configuration file (/pulsar-manager/pulsar-manager/application.properties) defaults to using HerdDB (which is not persisted), and the PostgreSQL related flags were commented out:
```ini
spring.datasource.schema=classpath:/META-INF/sql/herddb-schema.sql
spring.datasource.username=sa
spring.datasource.password=hdb
spring.datasource.initialization-mode=always

# postgresql configuration
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/pulsar_manager
#spring.datasource.username=postgres
#spring.datasource.password=postgres
```
In the PV, I only found files of postgresql database, but no herddb relates files.

**To Reproduce**
1. install the latest version of Chart will  reproduce it:
`helm install pulsar pulsar/pulsar`
