### ISSUE TITLE
Deployment using JWT authentication + Function Worker is not working properly

### ISSUE THREAD

**Issue by Mortom123** [apache/pulsar-helm-chart#472]
**Describe the bug**
Deploying Pulsar with JWT-Authentication enabled is impossible for me. Would be very glad for any advice :)

I populated the key for JWT authentification using this script (basically a very shortened `prepare_pulsar_release.sh` script using StreamNative's pulsarctl:
```
set -e

SCRIPT_DIR=$(dirname $0)
PULSAR_CTL=${SCRIPT_DIR}/pulsarctl
echo $SCRIPT_DIR
ls $SCRIPT_DIR
chmod +x "$PULSAR_CTL"

usage() {
    cat <<EOF
This script is used to generate token secret key for a given pulsar helm release.
Options:
       -h,--help                        prints the usage message
       --namespace                   the k8s namespace to install the pulsar helm chart
       --release                     the pulsar helm release name
       --pulsar-superusers
Usage:
    $0 --namespace pulsar --release pulsar --pulsar_superusers proxy-admin,broker-admin,admin,cim
EOF
}

symmetric=false

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --namespace)
    namespace="$2"
    shift
    shift
    ;;
    --release)
    release="$2"
    shift
    shift
    ;;
    --pulsar_superusers)
    pulsar_superusers="$2"
    shift
    shift
    ;;
    -h|--help)
    usage
    exit 0
    ;;
    *)
    echo "unknown option: $key"
    usage
    exit 1
    ;;
esac
done

function pulsar::jwt::generate_asymmetric_key_secret() {
    local secret_name="${release}-token-asymmetric-key"

    privatekeytmpfile=$(mktemp)
    trap "test -f $privatekeytmpfile && rm $privatekeytmpfile" RETURN
    publickeytmpfile=$(mktemp)
    trap "test -f $publickeytmpfile && rm $publickeytmpfile" RETURN
    echo "${PULSAR_CTL} token create-key-pair -a RS256 --output-private-key ${privatekeytmpfile} --output-public-key ${publickeytmpfile}"
    ${PULSAR_CTL} token create-key-pair -a RS256 --output-private-key ${privatekeytmpfile} --output-public-key ${publickeytmpfile}
    mv $privatekeytmpfile PRIVATEKEY
    mv $publickeytmpfile PUBLICKEY
    kubectl create secret generic ${secret_name} -n ${namespace} --from-file=PRIVATEKEY --from-file=PUBLICKEY
    rm PRIVATEKEY
    rm PUBLICKEY
}

function pulsar::jwt::get_secret() {
    local type=$1
    local tmpfile=$2
    local secret_name=$3
    echo ${secret_name}
    if [[ "${local}" == "true" ]]; then
        cp ${type} ${tmpfile}
    else
        echo "kubectl get -n ${namespace} secrets ${secret_name} -o jsonpath="{.data.${type}}" | base64 --decode > ${tmpfile}"
        kubectl get -n ${namespace} secrets ${secret_name} -o jsonpath="{.data['${type}']}" | base64 --decode > ${tmpfile}
    fi
}

function pulsar::jwt::generate_asymmetric_token() {
    role=$1
    echo "${role}"
    local token_name="${release}-token-${role}"
    local secret_name="${release}-token-asymmetric-key"

    privatekeytmpfile=$(mktemp)
    trap "test -f $privatekeytmpfile && rm $privatekeytmpfile" RETURN
    tokentmpfile=$(mktemp)
    trap "test -f $tokentmpfile && rm $tokentmpfile" RETURN
    pulsar::jwt::get_secret PRIVATEKEY ${privatekeytmpfile} ${secret_name}
    ${PULSAR_CTL} token create -a RS256 --private-key-file ${privatekeytmpfile} --subject ${role} 2&> ${tokentmpfile}
    newtokentmpfile=$(mktemp)
    tr -d '\n' < ${tokentmpfile} > ${newtokentmpfile}
    kubectl create secret generic ${token_name} -n ${namespace} --from-file="TOKEN=${newtokentmpfile}" --from-literal="TYPE=asymmetric"
}

pulsar::jwt::generate_asymmetric_key_secret

IFS=', ' read -r -a superusers <<< "$pulsar_superusers"
for user in "${superusers[@]}"
do
    echo "generate the token for $user" >&2
    pulsar::jwt::generate_asymmetric_token $user
done
```

`values.yaml` auth section is set to:
```
# Enable or disable broker authentication and authorization.
auth:
  authentication:
    enabled: true
    provider: "jwt"
    jwt:
      # Enable JWT authentication
      # If the token is generated by a secret key, set the usingSecretKey as true.
      # If the token is generated by a private key, set the usingSecretKey as false.
      usingSecretKey: false
  authorization:
    enabled: true
  superUsers:
    # broker to broker communication
    broker: "broker-admin"
    # proxy to broker communication
    proxy: "proxy-admin"
    # pulsar-admin client to broker/proxy communication
    client: "admin"
```

This results in the following error:
```
2024-03-18T16:43:06.465527897Z 2024-03-18T16:43:06,465+0000 [AsyncHttpClient-53-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://pulsar-broker-0.pulsar-broker.pulsar.svc.cluster.local:8080/admin/v2/persistent/public/functions/assignments] Failed to perform http put request: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
2024-03-18T16:43:06.566579093Z 2024-03-18T16:43:06,470+0000 [main] ERROR org.apache.pulsar.functions.worker.PulsarWorkerService - Error Starting up in worker
2024-03-18T16:43:06.566626250Z org.apache.pulsar.client.admin.PulsarAdminException$NotAuthorizedException: HTTP 401 Unauthorized
```

**To Reproduce**
1. Download release 2.10.4
2. Enable auth in `values.yaml` and turn on the function-worker component (if not already)
3. Use the script together with [pulsarctl ](https://github.com/streamnative/pulsarctl) to generate a pair of asymmetric keys and tokens, Put the `pulsarctl` as a sibling of the script and run: `generate_secrets.sh --namespace pulsar --release pulsar --pulsar_superusers proxy-admin,broker-admin,admin`
4. `helm install -n pulsar ...`

**Expected behavior**
I expect the helm chart to install successfully with no errors on side of the broker. 

**Additional context**
I am using an older version of the helm-chart (2.10.4)
