### ISSUE TITLE
Ingress hostname should not be required

### ISSUE THREAD

**Issue by toneill818** [apache/pulsar-helm-chart#50]
**Describe the bug**
When creating ingresses for services such as the proxy or pulsar-manager, the hostname value should optional. 

**To Reproduce**
1. Create an ingress without a hostname specified
```yaml
proxy:
  ingress:
    enabled: true
    path: "/pulsar-manager/"
```
2. Try installing or upgrading the chart

**Expected behavior**
An ingress should be created.

**Additional context**
I can submit a PR to make the hostname optional.
