### ISSUE TITLE
[Bug] pulsar-recovery and pulsar-bookie components do not supply metrics in the standard Prometheus format.

### ISSUE THREAD

**Issue by JWebDev** [apache/pulsar-helm-chart#555]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

apachepulsar/pulsar-all:4.0.0

### Minimal reproduce step

Is this a bug or is it designed that way? Is there any solution for this? Because 2 other components send metrics in the correct format and prometheus reads them without problems. I don't use `kube-prometheus-stack` I add annotations to each component for my prometheus server to pick up the metrics.
For example:
```
autorecovery:
  replicaCount: 1
  podMonitor:
    enabled: false
  annotations:
    prometheus.io/scrape: “true”
    prometheus.io/path: “/metrics”
    prometheus.io/port: “8000”
broker:
  replicaCount: 1
  podMonitor:
    enabled: false
  annotations:
    prometheus.io/scrape: “true”
    prometheus.io/path: “/metrics”
    prometheus.io/port: “8080”
```

``/metrics` are visible in all components, so they are there.

### What did you expect to see?

The same as in broker and zookeeper

```
pulsar-broker-0:/pulsar$ curl -I localhost:8080/metrics
HTTP/1.1 302 Found
Date: Sun, 01 Dec 2024 04:45:11 GMT
Location: http://localhost:8080/metrics/
Content-Length: 0
Server: Jetty(9.4.56.v20240826)

pulsar-zookeeper-0:/pulsar$ curl -I localhost:8000/metrics
HTTP/1.1 200 OK
Date: Sun, 01 Dec 2024 04:45:37 GMT
Content-Type: text/plain; version=0.0.4; charset=utf-8
Content-Length: 61427
Server: Jetty(9.4.56.v20240826)
```

### What did you see instead?

```
pulsar-recovery-0:/pulsar$ curl -I localhost:8000/metrics
HTTP/1.1 405 Method Not Allowed

pulsar-bookie-0:/pulsar$ curl -I localhost:8000/metrics
HTTP/1.1 405 Method Not Allowed
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
