### ISSUE TITLE
Deploy apache pulsar with external zookeeper

### ISSUE THREAD

**Issue by spesalvi** [apache/pulsar-helm-chart#566]
Hi All,

I have a zookeeper instance configured in a different namespace. I want to deploy the apache pulsar and use the zookeeper instance that I have in the other namespace.

In the values.yaml file i see an option to disable zookeeper. When I disable that, zookeeper instance is not created.

I also provided externalZookeeperServerList with my external zookeeper endpoints.

Now I notice that externalZookeeperServerList is used when zookeeper component is enabled. So, my zookeeper endpoints are not use by the helm chart and bookie and broker are always trying to connect to 127.0.0.1:2181.

Is there a way to configure pulsar to use external zookeeper instead.

Thanks,
Robert

**Comment by lhotari** [comment]
Reopening this since there seems to be changed which cause userProvidedZookeepers not to work as expected.

**Comment by lhotari** [comment]
@spesalvi This might work, would you be able to test it?
```yaml
userProvidedZookeepers: "zk01.example.com:2181,zk02.example.com:2181"
pulsar_metadata:
  configurationStore: "zk01.example.com:2181,zk02.example.com:2181"
```
