### ISSUE TITLE
Updating existing pulsar helm setup results to an error

### ISSUE THREAD

**Issue by Imunhatep** [apache/pulsar-helm-chart#67]
**Describe the bug**
Updating existing pulsar helm setup (e.g. changing replicas count)  results to an error

**To Reproduce**
```
helm upgrade --install pulsar -n pulsar -f values.yaml apache/pulsar

Error: UPGRADE FAILED: cannot patch "pulsar-bookie-init" with kind Job: Job.batch "pulsar-bookie-init" is invalid: spec.template:
... : field is immutable
```

**Expected behavior**
Pulsar setup is updated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Probably Jobs should be handled with helm hooks i.e.:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec: ...
```
