### ISSUE TITLE
Helm chart repo not tracking latest commits

### ISSUE THREAD

**Issue by nickelozz** [apache/pulsar-helm-chart#92]
**Describe the bug**
The pulsar [Helm chart repository](https://pulsar.apache.org/charts/index.yaml) is not tracking the last 2 commits from the master branch (https://github.com/apache/pulsar-helm-chart/commit/667e634af083c8326f2594c08b31f742a8f0d49a, https://github.com/apache/pulsar-helm-chart/commit/c2f672881e687d9b17ab1ad8cf5effa4dce6b4d2).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://pulsar.apache.org/charts/index.yaml'
2. See that the most up-to-date version is:
```
  - apiVersion: v1
    appVersion: 2.7.0
    created: "2021-01-08T05:27:15.548211942Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: bdbb841e75b5ed1fc9e65986def399690270c00c9282e0d616ddfa66faf2c558
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.0-1/pulsar-2.7.0-1.tgz
    version: 2.7.0-1
```
Alternatively, you can do ```helm pull apache/pulsar --version=2.7.0-1 --untar=true```

Notice that the following are missing:

- [Add basic PSP and RBAC for core components](https://github.com/apache/pulsar-helm-chart/commit/667e634af083c8326f2594c08b31f742a8f0d49a)
- [Updating pods on configmap change](https://github.com/apache/pulsar-helm-chart/commit/c2f672881e687d9b17ab1ad8cf5effa4dce6b4d2) Notice that this [action failed](https://github.com/apache/pulsar-helm-chart/runs/1666886666)

**Expected behaviour**
The latest chart version should include.
